import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ApolloClient from 'apollo-boost';
import { ApolloProvider } from 'react-apollo';

// Components
import NavBar from '../components/Navbar';
import BookList from '../components/BookList';

const client = new ApolloClient({
    uri: 'http://localhost:4000/graphql'
});

const Home: NextPage = () => {
  return (
    <ApolloProvider client={client}>
      <div className={styles.container}>
          <NavBar />
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className={styles.main}>
            <h1 className={styles.title}>
              GraphQL Reading List
            </h1>
            <BookList />
          </main>
      </div>
    </ApolloProvider>
  )
}

export default Home;
